---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      local_action: wait_for host={{ ansible_fqdn }} port=22 delay=120 timeout=900 state=started

    - name: "install python for Ansible."
      # Your code here

  roles:
    # Your code here
